defmodule FrontendWeb.Components.Sidebar do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  import FrontendWeb.Gettext

  #@doc "The name"
  #prop name, :string, default: "Guest"

  #@doc "The subtitle"
  #prop subtitle, :string

  #@doc "The color"
  #prop color, :string, values!: ["danger", "info", "warning"]

  @doc "Today's Date"
  slot todaysdate

  @doc "Today's Date"
  slot edges

  def render(assigns) do
    ~F"""
    <div class="sidebar"></div>
    """
  end
end
